// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.3
// source: hightop/ftu/v1/common.proto

package ftu

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StatusType int32

const (
	StatusType_Invalid StatusType = 0
	StatusType_Online  StatusType = 1
	StatusType_OffLine StatusType = 2
	StatusType_Warn    StatusType = 3
	StatusType_Alarm   StatusType = 4
)

// Enum value maps for StatusType.
var (
	StatusType_name = map[int32]string{
		0: "Invalid",
		1: "Online",
		2: "OffLine",
		3: "Warn",
		4: "Alarm",
	}
	StatusType_value = map[string]int32{
		"Invalid": 0,
		"Online":  1,
		"OffLine": 2,
		"Warn":    3,
		"Alarm":   4,
	}
)

func (x StatusType) Enum() *StatusType {
	p := new(StatusType)
	*p = x
	return p
}

func (x StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_hightop_ftu_v1_common_proto_enumTypes[0].Descriptor()
}

func (StatusType) Type() protoreflect.EnumType {
	return &file_hightop_ftu_v1_common_proto_enumTypes[0]
}

func (x StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusType.Descriptor instead.
func (StatusType) EnumDescriptor() ([]byte, []int) {
	return file_hightop_ftu_v1_common_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hightop_ftu_v1_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hightop_ftu_v1_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hightop_ftu_v1_common_proto_rawDescGZIP(), []int{0}
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode bool   `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hightop_ftu_v1_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_hightop_ftu_v1_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_hightop_ftu_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetRetCode() bool {
	if x != nil {
		return x.RetCode
	}
	return false
}

func (x *Result) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_hightop_ftu_v1_common_proto protoreflect.FileDescriptor

var file_hightop_ftu_v1_common_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x68, 0x69, 0x67, 0x68, 0x74, 0x6f, 0x70, 0x2f, 0x66, 0x74, 0x75, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x68,
	0x69, 0x67, 0x68, 0x74, 0x6f, 0x70, 0x2e, 0x66, 0x74, 0x75, 0x2e, 0x76, 0x31, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x34, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x47, 0x0a, 0x0a,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x4c, 0x69, 0x6e, 0x65, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x57, 0x61, 0x72, 0x6e, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x6c,
	0x61, 0x72, 0x6d, 0x10, 0x04, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x69, 0x67, 0x68, 0x74, 0x6f, 0x70, 0x2d, 0x69, 0x74, 0x65, 0x63,
	0x68, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x69,
	0x67, 0x68, 0x74, 0x6f, 0x70, 0x2f, 0x66, 0x74, 0x75, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x74, 0x75,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hightop_ftu_v1_common_proto_rawDescOnce sync.Once
	file_hightop_ftu_v1_common_proto_rawDescData = file_hightop_ftu_v1_common_proto_rawDesc
)

func file_hightop_ftu_v1_common_proto_rawDescGZIP() []byte {
	file_hightop_ftu_v1_common_proto_rawDescOnce.Do(func() {
		file_hightop_ftu_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_hightop_ftu_v1_common_proto_rawDescData)
	})
	return file_hightop_ftu_v1_common_proto_rawDescData
}

var file_hightop_ftu_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hightop_ftu_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hightop_ftu_v1_common_proto_goTypes = []interface{}{
	(StatusType)(0), // 0: hightop.ftu.v1.StatusType
	(*Empty)(nil),   // 1: hightop.ftu.v1.Empty
	(*Result)(nil),  // 2: hightop.ftu.v1.Result
}
var file_hightop_ftu_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hightop_ftu_v1_common_proto_init() }
func file_hightop_ftu_v1_common_proto_init() {
	if File_hightop_ftu_v1_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hightop_ftu_v1_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hightop_ftu_v1_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hightop_ftu_v1_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hightop_ftu_v1_common_proto_goTypes,
		DependencyIndexes: file_hightop_ftu_v1_common_proto_depIdxs,
		EnumInfos:         file_hightop_ftu_v1_common_proto_enumTypes,
		MessageInfos:      file_hightop_ftu_v1_common_proto_msgTypes,
	}.Build()
	File_hightop_ftu_v1_common_proto = out.File
	file_hightop_ftu_v1_common_proto_rawDesc = nil
	file_hightop_ftu_v1_common_proto_goTypes = nil
	file_hightop_ftu_v1_common_proto_depIdxs = nil
}
